### ISSUE TITLE
[SimpleCalculator] Module 01 - Calculator.cs link is dead

### ISSUE THREAD

**Issue by kazo0** [unoplatform/workshops#130]
Clicking on `source code` leads to a broken page

<img width="317" alt="image" src="https://github.com/unoplatform/workshops/assets/4793020/72ec8989-e234-44a7-b6e0-e1f1518f0721">

https://platform.uno/docs/articles/external/workshops/simple-calc/modules/MVUX-XAML/01-Build%20your%20first%20Project/README.html?tabs=wizard#prepare-the-project

**Comment by agneszitte** [comment]
@kazo0 I just pushed to prod the latest fixes. If you can clean your cache and test it again, please.
It is okay on my side when I tested it with the live website:
![image](https://github.com/unoplatform/workshops/assets/16295702/e2350272-498d-4e9d-af57-3cdb6c26d60f)
If it is okay we can close the issue. If not we will investigate.

**Comment by kazo0** [comment]
Yep works! @agneszitte

**Comment by agneszitte** [comment]
Thanks for the confirmation @kazo0, closing the issue then
