### ISSUE TITLE
[TubePlayer] FeedView missing in MVUX docs 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/workshops#166]
The workshop takes you to [Using a FeedView](https://platform.uno/docs/articles/external/uno.extensions/doc/Overview/Reactive/How-tos/SimpleFeed.html#using-a-feedview) many times across the steps, but the page seems to have been removed and it is just cached. It may have been moved, but our/Google search still display it when searching for FeedView https://github.com/unoplatform/uno-private/issues/1394

**Comment by morning4coffe-dev** [comment]
CC @nickrandolph, @eriklimakc, @agneszitte

**Comment by morning4coffe-dev** [comment]
https://platform.uno/docs/articles/external/uno.extensions/doc/Learn/Mvux/Tutorials/HowTo-SimpleFeed.html

**Comment by agneszitte** [comment]
Fixed with https://github.com/unoplatform/workshops/pull/168
