### ISSUE TITLE
Ask folks to clone to C:\code or similar due to MAX_PATH

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/workshops#18]
## What would you like to be added:

https://github.com/unoplatform/uno/issues/1564

## Why is this needed:

https://twitter.com/GeoffreyHuntley/status/1175098875926994945

**Comment by gagandeepp** [comment]
Can you assign this to me? Also help me how do you want the alert messages to be displayed?

**Comment by carldebilly** [comment]
Maybe it's correct now following Jérôme's PR https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/134
@jeromelaban
