### ISSUE TITLE
grammatical errors in the LICENSE file

### ISSUE THREAD

**Issue by vmr1532** [unoplatform/workshops#80]
## What would you like to be added:
    Correct the grammatical errors in the LICENSE file

## Why is this needed:
     For smoothness of Reading

## Anything else we need to know?
     NO

**Comment by UsmanAhmadSaeed** [comment]
I'd like to take this on

**Comment by UsmanAhmadSaeed** [comment]
I've proofread and checked and there are no errors as mentioned in this issue.
