### ISSUE TITLE
File naming convention MyControl.Droid.cs change to MyControl.Android.cs

### ISSUE THREAD

**Issue by artemious7** [unoplatform/workshops#82]
## Current behavior
[Here](https://github.com/unoplatform/workshops/tree/master/uno-bootcamp/modules/07-Working-with-Uno#ui-implementations) it says:

> Note usage of partial classes and the naming the convention of MyControl.cs, MyControl.iOS.cs, MyControl.Droid.cs, MyControl.wasm.cs.

## Expected behavior
But the actual naming convention for Android is `MyControl.Android.cs`

**Comment by davidjohnoliver** [comment]
The `.Droid.cs` convention is ok for app code - it matches the `AppName.Droid` convention for the namespace, which is preferred to avoid ambiguity errors with the `Android.Etc` system namespaces.

It's just the Uno repo _itself_ that for historical reasons uses the `.android.cs` suffix, and attaches semantic significance to it (files are globbed automatically).
